#!/bin/sh

echo "Installing android 4.2.2 into local maven repository..."

mvn install:install-file \
      -Dfile=$ANDROID_HOME/platforms/android-17/android.jar \
      -DgroupId=com.google.android \
      -DartifactId=android \
      -Dversion=4.2.2 \
      -Dpackaging=jar
