#!/bin/sh

echo "Installing android 4.3 into local maven repository..."

mvn install:install-file \
      -Dfile=$ANDROID_HOME/platforms/android-18/android.jar \
      -DgroupId=com.google.android \
      -DartifactId=android \
      -Dversion=4.3 \
      -Dpackaging=jar
